spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  datasource:
    url: ${DATASOURCE_URL:jdbc:h2:mem:testdb}
    username: ${DATASOURCE_USERNAME:sa}
    password: ${DATASOURCE_PASSWORD:}
    driver-class-name: ${DATASOURCE_DRIVER:org.h2.Driver}
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: ${HIBERNATE_DIALECT:org.hibernate.dialect.H2Dialect}
        jdbc.time_zone: UTC
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      platform: postgres
      mode: always

  web:
    resources:
      static-locations: classpath:/static/, file:uploads/

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${OKTA_ISSUER:https://trial-5957820.okta.com/oauth2/default}


logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

okta:
  oauth2:
    issuer: ${OKTA_ISSUER:https://trial-5957820.okta.com/oauth2/default}
    audience: api://default







