spring:
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 30MB
  datasource:
    url: ${DATASOURCE_URL}
    username: ${DATASOURCE_USERNAME}
    password: ${DATASOURCE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc.time_zone: UTC
        format_sql: true
        use_sql_comments: true
    open-in-view: false
    show-sql: true
    defer-datasource-initialization: true

  sql:
    init:
      platform: postgres
      mode: always

  web:
    resources:
      static-locations: classpath:/static/, file:uploads/

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE








