name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
      
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Backend tests
        run: ./gradlew clean test --info --stacktrace

      - name: Install frontend dependencies
        working-directory: frontend/vue-project
        run: npm ci

      - name: Frontend tests
        working-directory: frontend/vue-project
        run: npm run test -- --run
