name: CI

on: [ push ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: "adopt"
          java-version: 21

      - name: Make gradlew executable
        run: chmod +x gradlew

      - name: Run tests in backend directory
        run: ./gradlew clean test --info --stacktrace
